[tool.poetry]
name = "PawPalaceAPI"
version = "0.1.0"
description = "API for PawPalace app"
authors = ["g <zzu1u@list.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.2"
sqlalchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
